<?php

/**
 * @file
 * Contains qrmanager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qrmanager_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  if ($route_name === 'help.page.qrmanager') {
    $output = nl2br(file_get_contents(__DIR__ . '/README.txt'));
  }
  return $output;
}

/**
 * Implements hook_multiple_field_remove_button_field_types_alter().
 */
function qrmanager_multiple_field_remove_button_field_types_alter(array &$fieldTypes) {
  // Drupal multiple value field have no option to remove item.
  // @see https://www.drupal.org/project/drupal/issues/1038316
  // This optional hook adds ability to remove added items.
  // Requires "multiple_field_remove_button" module to be enabled.
  // @see https://www.drupal.org/project/multiple_fields_remove_button
  $fieldTypes[] = 'qrmanager';
}
